### ISSUE TITLE
Weird offset issue

### ISSUE THREAD

**Issue by jgrahame** [DatanoiseTV/AKWF_WaveForms#1]
I tried the 256+1 waveforms this morning with a wavetable oscillator that I'm working on for my hardware synth. It looks like there are some really weird offsets in the data - no negative values in many of the samples. Any idea what's going on?

**Comment by DatanoiseTV** [comment]
Hi! Can you please try to locate the Waveform at my Wavetool (http://tech.datanoise.net/wavetool/) and see how it looks there? (although this version is using 1024 length samples).

Hint: Use URL http://tech.datanoise.net/wavetool/imgs/AKWF_XXX.wav.png for direct waveform image.
so for example http://tech.datanoise.net/wavetool/imgs/AKWF_0001.wav.png

If it looks different from the 256+1 samples, then it is possible that my batch conversion of the 256+1 waveforms gone wrong.

Please let me know.

**Comment by DatanoiseTV** [comment]
Nevermind. This was a batch conversion error. It's fixed now :+1: 
Good luck with your Synth. I am building a hybrid analog / digital synth using this.

Please let me know if this has solved the issue for you, so I can close
this issue.

**Comment by jgrahame** [comment]
Hey. Those look much better! I'll try them out later this weekend. :)
